"""Pytest fixtures.

DATABASE_URL is overridden to a throwaway SQLite file BEFORE any app
module is imported, so the app's cached Settings singleton
(get_settings(), lru_cache'd) never sees the real Postgres URL from
.env during tests — DESIGN.md's own assumption is that SQLite is fine
for tests/ without Docker. IMAGE_BASE_DIR points at the real
sample_images/ folder generated by scripts/generate_sample_images.py,
so tests exercise the actual images rather than a separate fixture set.
RABBITMQ_URL is deliberately unreachable — job_service.create_job
swallows a failed publish on purpose (DESIGN.md §4 step 5), so the
API/DB layer under test doesn't need a real broker at all. Pointed at
the `.invalid` TLD (RFC 2606 — reserved, guaranteed to never resolve),
not RabbitMQ's real default host:port (localhost:5672): on a dev
machine actually running this project's Docker stack, that port has a
*real* broker listening, and guest:guest would reach a full AMQP
handshake and get rejected with a genuine auth-failure logged in that
real RabbitMQ's logs on every local test run. A real-but-closed
port/host isn't a clean substitute either — pika's connection workflow
retries a failed *connection attempt* a few times before giving up
(observed: several extra seconds per job-creating test), whereas a
hostname that fails at DNS resolution never gets that far — no socket,
no retry logic, just an immediate lookup failure.
"""
import os
from pathlib import Path

TEST_DB_PATH = Path(__file__).resolve().parent / "test.db"
SAMPLE_IMAGES_DIR = Path(__file__).resolve().parent.parent / "sample_images"

os.environ["DATABASE_URL"] = f"sqlite:///{TEST_DB_PATH}"
os.environ["IMAGE_BASE_DIR"] = str(SAMPLE_IMAGES_DIR)
os.environ.setdefault("RABBITMQ_URL", "amqp://guest:guest@rabbitmq.invalid:5672/")

import pytest  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from app.core.database import Base, SessionLocal, engine, init_db  # noqa: E402
from app.main import app  # noqa: E402


@pytest.fixture(autouse=True)
def _fresh_db():
    init_db()
    yield
    Base.metadata.drop_all(bind=engine)
    engine.dispose()
    try:
        if TEST_DB_PATH.exists():
            TEST_DB_PATH.unlink()
    except PermissionError:
        pass  # Windows occasionally still holds a handle briefly — next run's init_db() recreates it regardless


@pytest.fixture
def client():
    return TestClient(app)


@pytest.fixture
def db_session():
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()


@pytest.fixture
def sample_image_path():
    """A real, known-sharp generated image — see scripts/generate_sample_images.py."""
    return "checkerboard_sharp.png"


@pytest.fixture
def sample_blurry_image_path():
    return "checkerboard_blurry.png"
